# A sample Gemfile
source "https://rubygems.org"

gem 'thin'
gem 'sinatra'
gem 'sinatra-flash'
gem 'slim'
gem 'sass'
gem 'data_mapper'
gem 'pony'

group :development do
  gem 'sinatra-contrib'
  gem 'sqlite3'
  gem 'dm-sqlite-adapter'
end

group :production do
  gem 'pg'
  gem 'dm-postgres-adapter'
end
